name: Better Life Boutique
favicon: null
layout_spectrum: 0.24671
typography_spectrum: 0.51023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2bb673'
    - '#693178'
    - '#fafdfc'
    - '#c1abc5'
    - '#6e6e6e'
  brandStrength: 0.09222133713774383
  lightness: 0.6096213301643729
  saturation: 0.4584698183462024
  rhythmicContrast: 0.3020480733830482
purpose: []
