name: Better Life Boutique
favicon: null
layout_spectrum: 0.09580652764998376
typography_spectrum: 0.3047210790682584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.09222133713774383
  lightness: 0.6096213301643729
  saturation: 0.4584698183462024
  rhythmicContrast: 0.3020480733830482
purpose: []
